# Generated by Django 3.2.8 on 2021-10-28 01:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('house_number', models.DateField(blank=True, null=True, verbose_name='Died')),
                ('street', models.CharField(blank=True, choices=[('r', 'Remmington Avenue'), ('o', 'Ohlone Street'), ('a', 'Asgaard Street'), ('d', 'Dales Lane')], default='r', help_text='Host street', max_length=1)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description of the tool', max_length=1000)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.host')),
            ],
        ),
        migrations.CreateModel(
            name='ToolType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a tool type (e.g. Power Tool)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ToolInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this tool across whole collection', primary_key=True, serialize=False)),
                ('purchased', models.DateField(null=True)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Tool availability', max_length=1)),
                ('tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.tool')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
        migrations.AddField(
            model_name='tool',
            name='tool_type',
            field=models.ManyToManyField(help_text='Select a type for this tool', to='catalog.ToolType'),
        ),
    ]
