# Generated by Django 3.2.8 on 2021-10-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='house_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='House Number'),
        ),
    ]
