# Generated by Django 3.2.8 on 2021-10-30 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_toolinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set tool as returned'),)},
        ),
    ]
