# Generated by Django 3.2.8 on 2021-10-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_rename_blogpost_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(blank=True, choices=[('n', 'News'), ('a', 'Article'), ('c', 'Class')], default='n', help_text='News Type', max_length=1),
        ),
    ]
