# Generated by Django 3.2.8 on 2021-10-31 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_news_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='status',
            new_name='news_type',
        ),
    ]
