# Generated by Django 3.2.8 on 2021-10-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_rename_status_news_news_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_type',
            field=models.CharField(blank=True, choices=[('n', 'News'), ('a', 'Article'), ('w', 'Workshop')], default='n', help_text='News Type', max_length=1),
        ),
    ]
