# Generated by Django 3.2.8 on 2022-02-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_news_news_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='house_number',
            field=models.IntegerField(verbose_name='House Number'),
        ),
    ]
